services:
  tss:
    container_name: tss
    image: snowflower1408/utconnect_tss_fe
    build:
      context: .
      args:
        APP_NAME: 'tss'
        BUILD_ENV: 'production'

  esm:
    container_name: esm
    image: snowflower1408/utconnect_esm_fe
    build:
      context: .
      args:
        APP_NAME: 'esm'
        BUILD_ENV: 'production'

  gateway:
    image: nginxinc/nginx-unprivileged:1.27.0-alpine
    container_name: gateway_fe
    ports:
      - '80:80'
    volumes:
      - ./gateway.nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - tss
      - esm
